main_type: 'eval_saved_results_main' #'learn_fixed_theta_basic_main'
path_to_saved_model: '../output/dm_cvd/rayleigh/linear_delta_per_step_l10.01000_max_iter2000/model.pkl'
savedir_pre: '../output/dm_cvd/'

data_input_params:
    dataset_name: 'dm_cvd'
    saved_tr_te_idxs: '../data/dm_cvd/train_test_idxs_dm_cvd.pkl' #'../data/dm_cvd/dev_val_idxs_dm_cvd.pkl' #'../data/dm_cvd/train_test_idxs_dm_cvd.pkl'
    te_percent: -1.
    cov_time_representation: 'absolute'
    data_loading_params:
        paths: '../data/dm_cvd/all_data.pkl' 

model_params:
    model_type: 'linear_delta_per_step'
    dynamic_cov_dim: 185
    static_cov_dim: 20 

eval_params:
    eval_metrics: ['brier_score', 'c_index', 'c_index_truncated_at_S'] #['auc', 'c_index']
    dynamic_metrics:
        start_times: [0, 3, 8, 16, 30] #[.5, 1., 1.5, 2.]
        window_length: 28
        time_step: 7

train_params:
    learning_rate: .01
    batch_size: 20000
    conv_thresh: .00000001
    n_epoch_print: 500
    max_iter: 2000

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
        l1_reg: 0.01
