main_type: 'basic_main'
savedir_pre: '../output/mimic/'

data_input_params:
    dataset_name: 'mimic'
    #saved_tr_te_idxs: '../data/mimic/saved_tr_te_idxs_mimic.pkl'
    te_percent: 0.5
    cov_time_representation: 'absolute'
    data_loading_params:
        #paths: ['../data/synth/trajectories.pkl', '../data/synth/censoring_indicators.pkl', '../data/synth/censored_survival_times.pkl'] #, '../data/synth/static_covs.pkl']
        paths: '../data/mimic/mimic_debug.pkl'

model_params:
    model_type: 'linear_delta_per_step_num_visits_only'
    dynamic_cov_dim: 1 #103
    static_cov_dim: 1 # dummy static var for now that does nothing

eval_params:
    eval_metrics: ['c_index', 'c_index_truncated_at_S'] #['auc', 'c_index']
    dynamic_metrics:
        start_times: [60, 79, 123, 307]
        window_length: 100
        time_step: 20
        #start_times: [2., 4., 6., 8.]
        #window_length: 5
        #time_step: 1
        #start_times: [.5, 1., 1.5, 2.]
        #window_length: 3.
        #time_step: .25

train_params:
    learning_rate: .005
    batch_size: 10000
    conv_thresh: .00000001
    n_epoch_print: 50
    max_iter: 600

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
