main_type: 'landmarking_main' 
savedir_pre: '../output/pbc2/'

data_input_params:
    dataset_name: 'pbc2'
    saved_tr_te_idxs: '../data/PBC2/train_test_idxs_pbc2.pkl'
    te_percent: 0.1
    cov_time_representation: 'absolute'
    missing_ind_dim: 12
    data_loading_params:
        paths: '../data/PBC2/PBC2_cleaned_deephit.csv'
        one_hot_encode_dynamic_disc_vars: True
        timescale: 30

model_params:
    model_type: 'landmarked_RF'
    RF_num_trees: 250
    dynamic_cov_dim: 20
    static_cov_dim: 7 

eval_params:
    eval_metrics: ['brier_score', 'c_index', 'c_index_truncated_at_S'] 

    dynamic_metrics:
        start_times: [0, 118, 219, 300, 376]
        window_length: 219
        time_step: 54.75 

train_params:
    learning_rate: .001
    batch_size: 10000
    conv_thresh: .0000000000000000000000000000001
    n_epoch_print: 2000
    max_iter: 20000
    track_c_indices: False
    optimizer: 'adam'

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        l1_reg: 0.00
        l2_reg: 0.
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0.
