main_type: 'basic_main'
savedir_pre: '../output/synth/' #rayleigh/linear_theta_per_step'

data_input_params:
    dataset_name: 'simple_synth'
    te_percent: .20
    data_loading_params:
        paths: '../data/synth/simple_synth_theta_per_step.pkl'

model_params:
    model_type: 'linear_theta_per_step'
    dynamic_cov_dim: 1
    static_cov_dim: 1 # dummy static var for now that does nothing

eval_params:
    eval_metrics: ['auc_truncated_at_S', 'c_index_truncated_at_S'] #['auc', 'c_index']
    dynamic_metrics:
        start_times: [.2, .4, .6, .8, 1.]
        window_length: .6
        time_step: .05

train_params:
    learning_rate: .01
    batch_size: 20000
    conv_thresh: .00000001
    n_epoch_print: 50
    max_iter: 1000

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0. #.10
        delta_reg: 0.0 #1. #0.0 #.1 #.01
