main_type: 'landmarked_cox_main' # 'eval_saved_results_main'# #'learn_fixed_theta_basic_main'
savedir_pre: '../output/covid/'

data_input_params:
    dataset_name: 'covid'
    saved_tr_te_idxs: '../data/COVID-19/severity_train_test_idxs_covid.pkl' #'../data/COVID-19/severity_train_test_idxs_covid.pkl'
    te_percent: 0.1
    cov_time_representation: 'absolute'
    data_loading_params:
        #paths: ['../data/synth/trajectories.pkl', '../data/synth/censoring_indicators.pkl', '../data/synth/censored_survival_times.pkl'] #, '../data/synth/static_covs.pkl']
        paths: '../data/COVID-19/severity_processed_covid_data.pkl' #'../data/COVID-19/severity_processed_covid_data.pkl'

model_params:
    model_type: 'landmarked_cox'
    dynamic_cov_dim: 85 #345 #cur 345 #older data 248 #debug:85 or 102?
    static_cov_dim: 11 # dummy static var for now that does nothing

eval_params:
    eval_metrics: ['standard_c_index_truncated_at_S', 'c_index', 'c_index_truncated_at_S', 'auc', 'auc_truncated_at_S'] #['auc_truncated_at_S', 'c_index_truncated_at_S'] #['auc', 'c_index']

    dynamic_metrics:
        start_times: [0, 3, 4, 7, 11] #[2, 6, 15, 35] # old data[6., 10., 15., 24.]
        window_length: 12
        time_step: 3
        #start_times: [.5, 1., 1.5, 2.]
        #window_length: 3.
        #time_step: .25

train_params:
    learning_rate: .005
    batch_size: 15000
    conv_thresh: .01
    n_epoch_print: 50
    max_iter: 2000

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
        cox_l2_reg: 1.
