# TODO:
# 1. Create tr/te idxs and update the path variable below DONE
# 2. fix weird error with the extreme loss counts for the global logprob calc

main_type: 'learn_fixed_theta_basic_main' # 'eval_saved_results_main'# #'learn_fixed_theta_basic_main'
savedir_pre: '../output/pbc2/'
#device: 'cuda:3'

data_input_params:
    dataset_name: 'pbc2'
    saved_tr_te_idxs: '../data/PBC2/train_test_idxs_pbc2.pkl' #'../data/COVID-19/severity_dev_val_idxs_covid.pkl'
    te_percent: 0.1
    cov_time_representation: 'absolute'
    missing_ind_dim: 12
    data_loading_params:
        paths: '../data/PBC2/PBC2_cleaned_deephit.csv'
        one_hot_encode_dynamic_disc_vars: True
        

model_params:
    model_type: 'linear_delta_per_step'
    dynamic_cov_dim: 20 
    static_cov_dim: 7 
    total_dynamic_cov_dim: 32 # dynamic missing ind dim plus dynamic cov dim
#    param_init_scales: [300, 100]

eval_params:
    eval_metrics: ['brier_score', 'c_index', 'c_index_truncated_at_S'] #['auc_truncated_at_S', 'c_index_truncated_at_S'] #['auc', 'c_index']
    tracked_eval_metrics: ['c_index', 'c_index_truncated_at_S']

    dynamic_metrics:
        start_times: [0, 3.933, 7.3, 10., 12.53] #logscale: [1, 4.779, 5.3936, 5.7071, 5.9322] #days scale [0, 118, 219, 300, 376] 
        window_length: 10 #5.707 #300
        time_step: 2.5 #150
        #start_times: [.5, 1., 1.5, 2.]
        #window_length: 3.
        #time_step: .25

train_params:
    learning_rate: .001
    batch_size: 10000
    conv_thresh: .0000000000000000000000000000001
    n_epoch_print: 2000
    max_iter: 20000
    track_c_indices: False
    optimizer: 'adam'

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        l1_reg: 0.00
        l2_reg: 0. #0.001
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
