main_type: 'validate_RNN_hidden_dim_main'
savedir_pre: '../output/dm_cvd/'

data_input_params:
    dataset_name: 'dm_cvd'
    saved_tr_te_idxs: '../data/dm_cvd/train_test_idxs_dm_cvd.pkl' #'../data/dm_cvd/train_test_idxs_dm_cvd_mini.pkl' #
#    te_percent: 0.1 #not used if saved_tr_te_idxs are given unless debugging
    saved_dev_val_idxs: '../data/dm_cvd/dev_val_idxs_dm_cvd.pkl' #'../data/dm_cvd/dev_val_idxs_dm_cvd_mini.pkl' #
    cov_time_representation: 'absolute'
    data_loading_params:
        #paths: ['../data/synth/trajectories.pkl', '../data/synth/censoring_indicators.pkl', '../data/synth/censored_survival_times.pkl'] #, '../data/synth/static_covs.pkl']
        paths: '../data/dm_cvd/all_data.pkl' #mini_preprocessed_data.pkl' # all_data.pkl

model_params:
    model_type: 'RNN_delta_per_step'
    dynamic_cov_dim: 186 #older data: 248 
    #hidden_dim: 10 
    hidden_dims_to_validate: [8, 64, 128, 256]
    static_cov_dim: 4

eval_params:
    eval_metrics: ['standard_c_index_truncated_at_S', 'c_index', 'c_index_truncated_at_S'] 
    dynamic_metrics:
        start_times: [0, 3, 8, 16, 30] #[6., 10., 15., 24.]
        window_length: 28
        time_step: 7
        #start_times: [.5, 1., 1.5, 2.]
        #window_length: 3.
        #time_step: .25

train_params:
    learning_rate: .01 #RAYLEIGH: 0.01 #Gompertz .001
    batch_size: 10000 # this is full batch gradient descent since so large
    conv_thresh: .00000001
    n_epoch_print: 50
    max_iter: 2000

    diagnostic_params:

    loss_params:

        distribution_type: 'rayleigh' #'gompertz'  
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
