main_type: 'landmarking_main' # 'eval_saved_results_main'# #'learn_fixed_theta_basic_main'
savedir_pre: '../output/covid/'

data_input_params:
    dataset_name: 'covid'
    saved_tr_te_idxs: '../data/COVID-19/severity_train_test_idxs_covid.pkl' #'../data/COVID-19/severity_dev_val_idxs_covid.pkl' #'../data/COVID-19/severity_train_test_idxs_covid.pkl' #'../data/COVID-19/severity_dev_val_idxs_covid.pkl'
    te_percent: 0.1 #not used if saved_tr_te_idxs are given unless debugging
    cov_time_representation: 'absolute'
    data_loading_params:
        paths: '../data/COVID-19/severity_processed_covid_data.pkl'

model_params:
    model_type: 'landmarked_RF'
    RF_num_trees: 250
    dynamic_cov_dim: 345 
    static_cov_dim: 56 

eval_params:
    eval_metrics: ['brier_score', 'c_index', 'c_index_truncated_at_S'] #['auc_truncated_at_S', 'c_index_truncated_at_S'] #['auc', 'c_index']

    dynamic_metrics:
        start_times: [0, 3, 4, 7, 11]
        window_length: 12
        time_step: 3

train_params:
    learning_rate: .001
    batch_size: 10000
    conv_thresh: .0000000000000000000000000000001
    n_epoch_print: 2000
    max_iter: 20000
    track_c_indices: False
    optimizer: 'adam'

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        l1_reg: 0.00
        l2_reg: 0. #0.001
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
