main_type: 'basic_main'
savedir: '../output/synth/linear_constant_delta_weibull'

data_input_params:
    dataset_name: 'dm_cvd'
    te_percent: .20
    data_loading_params:
        #paths: ['../data/synth/trajectories.pkl', '../data/synth/censoring_indicators.pkl', '../data/synth/censored_survival_times.pkl'] #, '../data/synth/static_covs.pkl']
        paths: '../data/dm_cvd/data_dev.pkl'

model_params:
    model_type: 'embedding_linear_constant_delta'
    dynamic_cov_dim: 187
    static_cov_dim: 4

eval_params:
    c_index:
        start_times: [0.]
        window_length: 10.
        time_step: 2.
        
    

train_params:
    learning_rate: 1.
    batch_size: 10000
    conv_thresh: .00000001
    n_epoch_print: 100
    max_iter: 100
    pretraining:
        pretraining_lr: 1.
        pretraining_max_iter: 100
        regular_training_max_iter: 1000
        regular_training_lr: .05

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        theta_drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #.1 #.01
