main_type: 'basic_main'
savedir: '../output/synth/exp'
data_input_params:
    dataset_name: 'synth'
    data_loading_params:
        paths: ['../data/synth/trajectories.pkl', '../data/synth/censoring_indicators.pkl', '../data/synth/censored_survival_times.pkl']

model_params:
    model_type: 'theta_per_step'
    dynamic_cov_dim: 1
    dropout: 1.
    hidden_dim: 2

train_params:
    learning_rate: .05
    batch_size: 50
    conv_thresh: .00000001
    n_epoch_print: 50
    max_iter: 500
    pretraining:
        pretraining_max_iter: 1000
        regular_training_max_iter: 1000
        regular_training_lr: .005

    diagnostic_params:

    loss_params:
        distribution_type: 'exponential'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        theta_drift_reg: .1
        global_diff_reg: .1
