main_type: 'eval_saved_results_main' #eval_saved_results_main #'learn_fixed_theta_basic_main'
path_to_saved_model: '../output/covid/rayleigh/RNN_delta_per_step_hdim64_l20.00100_max_iter2000/model.pkl' #for use to load a pre-saved model to evaluate, plot results etc
savedir_pre: '../output/covid/'
#device: 'cuda:4'

data_input_params:
    dataset_name: 'covid'
    saved_tr_te_idxs: '../data/COVID-19/severity_train_test_idxs_covid.pkl' #'../data/COVID-19/severity_train_test_idxs_covid.pkl' #'../data/COVID-19/severity_dev_val_idxs_covid.pkl'
    te_percent: 0.1 #not used if saved_tr_te_idxs are given unless debugging
    cov_time_representation: 'absolute'
    data_loading_params:
        paths: '../data/COVID-19/severity_processed_covid_data.pkl'

model_params:
    model_type: 'RNN_delta_per_step'
    hidden_dim: 64
    dynamic_cov_dim: 345 # older data:248 #103
    static_cov_dim: 56 # dummy static var for now that does nothing
    dropout: .0

eval_params:
    eval_metrics: ['brier_score', 'c_index', 'c_index_truncated_at_S'] 
    tracked_eval_metrics: ['c_index', 'c_index_truncated_at_S']
    dynamic_metrics:
        start_times: [0, 3, 4, 7, 11] 
        window_length: 12
        time_step: 3
        #start_times: [.5, 1., 1.5, 2.]
        #window_length: 3.
        #time_step: .25

train_params:
    learning_rate: .01 #old: .01
    batch_size: 10000
    conv_thresh: .000000001
    n_epoch_print: 500
    max_iter: 2000 #10000
    track_c_indices: False

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh' #'gompertz' #
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
        l1_reg: 0.000
        l2_reg: 0.0001 #0.0001
