main_type: 'basic_main'
savedir_pre: '../output/covid/'

data_input_params:
    dataset_name: 'covid'
    saved_tr_te_idxs: #'../data/COVID-19/train_test_idxs_covid.pkl'
    te_percent: 0.25 # not used if saved_tr_te_idxs is given in config
    cov_time_representation: 'absolute'
    data_loading_params:
        #paths: ['../data/synth/trajectories.pkl', '../data/synth/censoring_indicators.pkl', '../data/synth/censored_survival_times.pkl'] #, '../data/synth/static_covs.pkl']
        paths: '../data/COVID-19/processed_covid_data.pkl'

model_params:
    model_type: 'RNN_delta_per_step'
    dynamic_cov_dim: 248 #103
    static_cov_dim: 11 # dummy static var for now that does nothing
    hidden_dim: 32
    dropout: .3

eval_params:
    eval_metrics: ['c_index', 'c_index_truncated_at_S'] #['auc_truncated_at_S', 'c_index_truncated_at_S'] #['auc', 'c_index']
    dynamic_metrics:
        start_times: [6., 10., 15., 24.]
        window_length: 20
        time_step: 5
        #start_times: [.5, 1., 1.5, 2.]
        #window_length: 3.
        #time_step: .25

train_params:
    learning_rate: .005
    batch_size: 10000
    conv_thresh: .00000001
    n_epoch_print: 50
    max_iter: 10000

    diagnostic_params:

    loss_params:
        distribution_type: 'rayleigh'
        avg_per_seq: True
        step_ahead_cov_reg: .0
        drift_reg: 0.
        global_diff_reg: 0.
        delta_reg: 0. #0.1 #.01
